-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         10.4.24-MariaDB - Source distribution
-- SO del servidor:              Linux
-- HeidiSQL Versión:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Volcando estructura de base de datos para FACTURA
CREATE DATABASE IF NOT EXISTS `FACTURA` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `FACTURA`;

-- Volcando estructura para tabla FACTURA.ARTICULO
CREATE TABLE IF NOT EXISTS `ARTICULO` (
  `ID` int(11) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `ART_DESCRIPCION` text DEFAULT NULL,
  `ART_PRECIO_UNIDAD` int(10) unsigned DEFAULT NULL,
  `ART_CODIGO` int(11) unsigned DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla FACTURA.ARTICULO: ~11 rows (aproximadamente)
INSERT INTO `ARTICULO` (`ID`, `ART_DESCRIPCION`, `ART_PRECIO_UNIDAD`, `ART_CODIGO`) VALUES
	(00000000001, '', 23, 445),
	(00000000002, '22', 59, 7593),
	(00000000003, NULL, 5, NULL),
	(00000000004, NULL, NULL, 3),
	(00000000005, NULL, 598, NULL),
	(00000000006, NULL, 598, NULL),
	(00000000007, NULL, 598, NULL),
	(00000000008, NULL, 598, NULL),
	(00000000009, NULL, 598, NULL),
	(00000000010, NULL, 598, NULL),
	(00000000011, NULL, 598, NULL),
	(00000000012, NULL, 598, NULL),
	(00000000013, NULL, 598, NULL);

-- Volcando estructura para tabla FACTURA.CLIENTE
CREATE TABLE IF NOT EXISTS `CLIENTE` (
  `ID` int(10) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `CLI_NOMBRE` char(50) NOT NULL,
  `CLI_DOMICILIO` char(50) DEFAULT NULL,
  `CLI_LOCALIDAD` char(50) DEFAULT NULL,
  `CLI_CODIGO_POSTAL` int(5) unsigned DEFAULT NULL,
  `CLI_CODIGO` int(5) unsigned DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla FACTURA.CLIENTE: ~2 rows (aproximadamente)
INSERT INTO `CLIENTE` (`ID`, `CLI_NOMBRE`, `CLI_DOMICILIO`, `CLI_LOCALIDAD`, `CLI_CODIGO_POSTAL`, `CLI_CODIGO`) VALUES
	(0000000001, 'RUBEN', 'FASDFGDSF', 'ASDF', 521324, 55),
	(0000000002, 'AAARSDR', 'GHHHHHHF', 'GGHFRTILKI', 555, 99);

-- Volcando estructura para tabla FACTURA.DETALLE_FACTURA
CREATE TABLE IF NOT EXISTS `DETALLE_FACTURA` (
  `ID` int(10) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `CANTIDAD_VENDIDA` int(10) unsigned NOT NULL,
  `CODIGO_ART` int(10) unsigned NOT NULL,
  `NRO_FACT` int(10) unsigned NOT NULL,
  `precio_unitario` int(11) DEFAULT NULL,
  `costo_unitario` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE,
  KEY `FK_DETALLE_FACTURA_ARTICULO` (`CODIGO_ART`),
  KEY `FK_DETALLE_FACTURA_FACTURA` (`NRO_FACT`),
  CONSTRAINT `FK_DETALLE_FACTURA_ARTICULO` FOREIGN KEY (`CODIGO_ART`) REFERENCES `ARTICULO` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_DETALLE_FACTURA_FACTURA` FOREIGN KEY (`NRO_FACT`) REFERENCES `FACTURA` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla FACTURA.DETALLE_FACTURA: ~2 rows (aproximadamente)
INSERT INTO `DETALLE_FACTURA` (`ID`, `CANTIDAD_VENDIDA`, `CODIGO_ART`, `NRO_FACT`, `precio_unitario`, `costo_unitario`) VALUES
	(0000000001, 5, 1, 1, NULL, NULL),
	(0000000002, 6, 2, 2, NULL, NULL);

-- Volcando estructura para tabla FACTURA.FACTURA
CREATE TABLE IF NOT EXISTS `FACTURA` (
  `ID` int(11) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `FAC_FECHA` date NOT NULL,
  `FAC_CONDICION_PAGO` char(50) NOT NULL,
  `FAC_IMPORTE_NETO` char(50) NOT NULL,
  `FAC_COD_VENDEDOR` int(10) unsigned NOT NULL,
  `FAC_COD_CLIENTE` int(10) unsigned NOT NULL,
  `FAC_NUM` int(10) unsigned NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_FACTURA_CLIENTE` (`FAC_COD_CLIENTE`),
  KEY `FK_FACTURA_VENDEDOR` (`FAC_COD_VENDEDOR`),
  CONSTRAINT `FK_FACTURA_CLIENTE` FOREIGN KEY (`FAC_COD_CLIENTE`) REFERENCES `CLIENTE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_FACTURA_VENDEDOR` FOREIGN KEY (`FAC_COD_VENDEDOR`) REFERENCES `VENDEDOR` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla FACTURA.FACTURA: ~2 rows (aproximadamente)
INSERT INTO `FACTURA` (`ID`, `FAC_FECHA`, `FAC_CONDICION_PAGO`, `FAC_IMPORTE_NETO`, `FAC_COD_VENDEDOR`, `FAC_COD_CLIENTE`, `FAC_NUM`) VALUES
	(00000000001, '2007-11-15', 'TARJETA', '2', 2, 1, 2),
	(00000000002, '2020-06-15', 'CREDITO', '55', 1, 2, 5);

-- Volcando estructura para función FACTURA.GananciaVentas
DELIMITER //
CREATE FUNCTION `GananciaVentas`(`_Ano` INT,
	`_Mes` INT
) RETURNS double
    READS SQL DATA
BEGIN
    DECLARE Ganancia DECIMAL(10, 2);
    DECLARE Precio DECIMAL(10, 2);
    DECLARE Cantidad INT;
    DECLARE Costo DECIMAL(10, 2);
    DECLARE Final TINYINT DEFAULT 0;
   
    DECLARE CV CURSOR FOR
    SELECT DETALLE_FACTURA.precio_unitario, DETALLE_FACTURA.costo_unitario,DETALLE_FACTURA.CANTIDAD_VENDIDA 
    FROM DETALLE_FACTURA df
    JOIN FACTURA.FACTURA f ON df.nro_factura = f.nro_factura
    WHERE costo_unitario > 0 AND YEAR(f.fecha_factura) = _Ano AND MONTH(f.fecha_factura) = _Mes;
   
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET Final = 1;
   
    SET Ganancia = 0;
    OPEN CV;
   
    my_loop: LOOP
        FETCH CV INTO Precio, Costo, Cantidad;
        IF Final = 1 THEN
            LEAVE my_loop;
        END IF;
        SET Ganancia = Ganancia + ((Precio - Costo) * Cantidad);
    END LOOP my_loop;
   
    CLOSE CV;
   
    RETURN Ganancia;
END//
DELIMITER ;

-- Volcando estructura para tabla FACTURA.VENDEDOR
CREATE TABLE IF NOT EXISTS `VENDEDOR` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `VEN_NOMBRE` char(50) NOT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4;

-- Volcando datos para la tabla FACTURA.VENDEDOR: ~5 rows (aproximadamente)
INSERT INTO `VENDEDOR` (`ID`, `VEN_NOMBRE`) VALUES
	(1, 'ANTONIO'),
	(2, 'RICARDO'),
	(3, 'ALBA'),
	(4, '[INDRID]'),
	(5, 'ALBAVENDEDOR');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
