/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora2;

import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author rutvac
 */
public class calculadora2 extends javax.swing.JFrame {

    /**
     * Creates new form calculadora2
     */
    public calculadora2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldnum1 = new javax.swing.JTextField();
        jTextFieldnum2 = new javax.swing.JTextField();
        jRadioButtonSumatorio = new javax.swing.JRadioButton();
        jRadioButtonProductorio = new javax.swing.JRadioButton();
        jRadioButtonExponencial = new javax.swing.JRadioButton();
        jButtonCalcula = new javax.swing.JButton();
        jLabelRes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(255, 153, 153));

        jTextFieldnum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnum1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonSumatorio);
        jRadioButtonSumatorio.setText("Sumatorio");
        jRadioButtonSumatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSumatorioActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonProductorio);
        jRadioButtonProductorio.setText("Productorio");

        buttonGroup1.add(jRadioButtonExponencial);
        jRadioButtonExponencial.setText("Exponencial");

        jButtonCalcula.setText("Calcula");
        jButtonCalcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculaActionPerformed(evt);
            }
        });

        jLabelRes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jTextFieldnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jTextFieldnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButtonExponencial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButtonProductorio)
                    .addComponent(jRadioButtonSumatorio)
                    .addComponent(jButtonCalcula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelRes, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldnum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldnum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jRadioButtonSumatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonProductorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonExponencial)
                .addGap(27, 27, 27)
                .addComponent(jButtonCalcula)
                .addGap(18, 18, 18)
                .addComponent(jLabelRes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldnum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnum1ActionPerformed

    private void jButtonCalculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculaActionPerformed
        // TODO add your handling code here:
        if (jTextFieldnum1.getText().isEmpty() || jTextFieldnum2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tienes que introducir un numero si o si", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (buttonGroup1.isSelected(null)) {
            JOptionPane.showMessageDialog(this, "Tienes que seleccionar una opcion  si o si", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            if (jRadioButtonSumatorio.isSelected()) {
                if (Integer.parseInt(jTextFieldnum1.getText()) > Integer.parseInt(jTextFieldnum2.getText())) {
                    JOptionPane.showMessageDialog(this, "Tienes que poner el primer numero menor", "Aviso", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                int res = 0;
                for (int i = Integer.parseInt(jTextFieldnum1.getText()); i <= Integer.parseInt(jTextFieldnum2.getText()); i++) {
                    res += i;
                }
                jLabelRes.setText(String.valueOf(res));
            }
            if (jRadioButtonProductorio.isSelected()) {
                if (Integer.parseInt(jTextFieldnum1.getText()) > Integer.parseInt(jTextFieldnum2.getText())) {
                    JOptionPane.showMessageDialog(this, "Tienes que poner el primer numero menor", "Aviso", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                int res = Integer.parseInt(jTextFieldnum1.getText());
                for (int i = Integer.parseInt(jTextFieldnum1.getText()) + 1; i <= Integer.parseInt(jTextFieldnum2.getText()); i++) {
                    res *= i;
                }
                jLabelRes.setText(String.valueOf(res));
            }
            if (jRadioButtonExponencial.isSelected()) {
                int res = 0;
                int num1 = Integer.parseInt(jTextFieldnum1.getText());
                int num2 = Integer.parseInt(jTextFieldnum2.getText());
                res = (int) Math.pow(num1, num2);

                jLabelRes.setText(String.valueOf(res));
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e, "Aviso", JOptionPane.WARNING_MESSAGE);

            System.out.println("Error: Ingresa valores numéricos en los campos");
        }
    }//GEN-LAST:event_jButtonCalculaActionPerformed

    private void jRadioButtonSumatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSumatorioActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jRadioButtonSumatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCalcula;
    private javax.swing.JLabel jLabelRes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonExponencial;
    private javax.swing.JRadioButton jRadioButtonProductorio;
    private javax.swing.JRadioButton jRadioButtonSumatorio;
    private javax.swing.JTextField jTextFieldnum1;
    private javax.swing.JTextField jTextFieldnum2;
    // End of variables declaration//GEN-END:variables
}
