/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inicisessio;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Arrays;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author rutvac
 */
public class inicisessio extends javax.swing.JFrame {

    /**
     * Creates new form inicisessio
     */
    public inicisessio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelUsu = new javax.swing.JLabel();
        jLabelContra = new javax.swing.JLabel();
        jTextFieldUsu = new javax.swing.JTextField();
        jButtonInicia = new javax.swing.JButton();
        jPasswordFieldContra = new javax.swing.JPasswordField();
        jButtonCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelUsu.setText("Usuario");

        jLabelContra.setText("Contraseña");

        jButtonInicia.setText("Iniciar Sesion");
        jButtonInicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciaActionPerformed(evt);
            }
        });

        jButtonCrear.setText("Crear usuario");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonInicia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jButtonCrear))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUsu)
                            .addComponent(jLabelContra))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldUsu)
                            .addComponent(jPasswordFieldContra, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsu)
                    .addComponent(jTextFieldUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContra)
                    .addComponent(jPasswordFieldContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInicia)
                    .addComponent(jButtonCrear))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciaActionPerformed
        // TODO add your handling code here:
        try {
            if (jTextFieldUsu.getText().contains(";")) {
                JOptionPane.showMessageDialog(this, "El usuario lleva el caracter ; ", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (Arrays.toString(jPasswordFieldContra.getPassword()).contains(";")) {
                JOptionPane.showMessageDialog(this, "La contraseña lleva el caracter ; ", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }
            File wr = new File("users.txt");
            ArrayList<String> usu = new ArrayList<>();
            ArrayList<String> con = new ArrayList<>();
            Scanner sc = new Scanner(wr);

            while (sc.hasNextLine()) {
                String users = sc.nextLine();
                String[] separa = users.split(";");
                usu.add(separa[0]);
                con.add(separa[1]);
            }
            for (int i = 0; i < usu.size(); i++) {
                if (usu.get(i).equals(jTextFieldUsu.getText()) && String.valueOf(con.get(i)).equals(String.valueOf(Arrays.toString(jPasswordFieldContra.getPassword())))) {
                    JOptionPane.showMessageDialog(this, "Usuario y contraseña correctos ", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    jTextFieldUsu.setText("");
                    jPasswordFieldContra.setText("");
                    return;

                }

            }
            JOptionPane.showMessageDialog(this, "Usuario y contraseña incorrectos ", "Aviso", JOptionPane.WARNING_MESSAGE);
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error al buscar el fichero", "Aviso", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Hay un error que no se tiene precisto", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonIniciaActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        try {
            // TODO add your handling code here:
            FileWriter wr = new FileWriter("users.txt", true);
            if (jTextFieldUsu.getText().contains(";")) {
                JOptionPane.showMessageDialog(this, "El usuario lleva el caracter ; ", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (Arrays.toString(jPasswordFieldContra.getPassword()).contains(";")) {
                JOptionPane.showMessageDialog(this, "La contraseña lleva el caracter ; ", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }
            wr.write(jTextFieldUsu.getText() + ";" + Arrays.toString(jPasswordFieldContra.getPassword()) + "\n");
            wr.close();
            JOptionPane.showMessageDialog(this, "Usuario creado correctamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            jTextFieldUsu.setText("");
            jPasswordFieldContra.setText("");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al buscar el fichero", "Aviso", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButtonCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicisessio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicisessio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicisessio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicisessio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicisessio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonInicia;
    private javax.swing.JLabel jLabelContra;
    private javax.swing.JLabel jLabelUsu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldContra;
    private javax.swing.JTextField jTextFieldUsu;
    // End of variables declaration//GEN-END:variables
}
