UPDATE CLIENTE SET CLI_NOMBRE='RUBEN E HIJOS' WHERE CLI_NOMBRE='RUBEN';
UPDATE FACTURA SET FAC_IMPORTE_NETO='2' WHERE FAC_IMPORTE_NETO='26';
INSERT INTO VENDEDOR (VEN_NOMBRE) VALUES ('ALBAVENDEDOR');
INSERT INTO ARTICULO (ART_PRECIO_UNIDAD) VALUES ('5');
INSERT INTO ARTICULO (ART_CODIGO) VALUES ('3');